Annotations
vaticle/typeql pull request #282
Opened 2023-05-10 17:13 UTC by dmitrii-ubskii

**For the title of this PR:** please follow the grammatical rules of a usual publication title, without capitalisation (except for the first letter). Thus, the title should NOT CONTAIN CODE: no dots, no parentheses, no backticks, no brackets, etc. It needs to be distinctive (not detailed) and succinct (not lengthy). Details of this PR will go in the description. **For the description of this PR:** please replace every line in curly brackets ( { like this } ) with an appropriate description following the guidance. Finally, **please remove this paragraph**.

## What is the goal of this PR?

{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related GitHub issues. This section will be automatically compiled into the release notes, so please:
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new product behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.
  - Use the _Royal We_: _"We"_ made changes, not _"I"_ made changes. }

## What are the changes implemented in this PR?

{ Please explain what you implemented, why your changes are the best way to achieve the goal(s) above. Please describe every method, class and package, by explaining:
  - its responsibility, 
  - how it's expected to behave, and 
  - how it relates to the adjacent methods/classes/packages it interacts with. 

This would allow the reviewer to understand your intentions in the code much better. If you're adding new classes, make sure these explanations are also included in the class header comments. Last but not least, please reference the GitHub issues to be automatically closed, such like 'closes #number'. }

2023-05-15 09:11 UTC, dmitrii-ubskii commented on rust/parser/test/mod.rs
> +            ))
`from_ymd`, `from_hms`, and `from_hms_millis` are all deprecated, and their new `_opt` variants (which validate the input and return an `Option<T>`) are to be used instead.

2023-05-15 09:12 UTC, dmitrii-ubskii commented on rust/parser/test/mod.rs
> +    let expected = typeql_match!(var("x").owns(("name", Key))).get(["x"]);
`KEY` the constant (which used to stand for `IsKey::Yes`) is replaced by `[Annotation::]Key` the enum variant.

2023-05-15 09:14 UTC, dmitrii-ubskii commented on rust/pattern/constraint/thing/value.rs
> +                    Err(TypeQLError::InvalidConstraintDatetimePrecision(*date_time))?
`NaiveDateTime` is plain old data that implements `Copy`, i.e. it is never moved.

2023-05-15 09:15 UTC, dmitrii-ubskii commented on rust/pattern/schema/rule.rs
> -        string::indent,
Became unused after we changed how rules are formatted.

2023-05-15 09:16 UTC, dmitrii-ubskii commented on rust/tests/behaviour/main.rs
> +    parse_query(step.docstring.as_ref().unwrap()).unwrap()
Remove unnecessary double referencing.

2023-05-15 09:17 UTC, dmitrii-ubskii commented on rust/pattern/constraint/type_/owns.rs
> +    pub annotations: HashSet<Annotation>,
Potentially could be a bitset instead, which may or may not save a bit of overhead.

2023-05-15 09:18 UTC, dmitrii-ubskii commented on rust/pattern/constraint/type_/owns.rs
> +    pub(crate) fn new(
`OwnsConstraint` is now created directly by the parser without relying on `from()`. `From` impls now don't have to accept `Option<T>` for the overridden attribute label: it's either present or it isn't.

2023-05-15 09:27 UTC, dmitrii-ubskii commented on rust/pattern/constraint/type_/owns.rs
>  }
A little more systematic in how the `From<T>` are implemented for the constraint:

- `&str`/`String` are transformed into `Label`;
- `Label`, `Type`, and `UnboundVariable` are all transformed into `TypeVariable`;
- single `Annotation` — into an array of `Annotation`s.

2023-05-15 09:31 UTC, dmitrii-ubskii commented on rust/pattern/constraint/type_/owns.rs
>  }
These could potentially be generated by a clever macro based on the rules like the above, to simplify the cognitive load.

2023-05-23 14:46 UTC, flyingsilverfin requested changes

2023-05-23 14:46 UTC, flyingsilverfin commented on rust/parser/mod.rs
> +                        visit_type(constraint.consume_expected(Rule::type_)).into_type_variable();
this line looks too short / awkwardly split up. I think it would look  better like:
```
let type = visit_type(...)
    .into_type_variable()
```

2023-05-23 14:46 UTC, flyingsilverfin commented on rust/pattern/constraint/type_/owns.rs
> +impl From<Type> for OwnsConstraint {
After investigation we found that `Label.Type` shouldn't exist outside of the Parser implementation, which will also require that the constructors here for `Type` will disappear.

2023-05-23 14:46 UTC, flyingsilverfin commented on rust/pattern/constraint/type_/owns.rs
> +    pub annotations: HashSet<Annotation>,
Ths should be a list/vector, since we should store the user's query faithfully

2023-05-23 16:22 UTC, flyingsilverfin approved these changes

2023-05-23 16:52 UTC, merged